/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#363940",
        "secondary": "#e0b6ff",
        "surface-container-lowest": "#0b0e14",
        "primary-fixed": "#9cf0ff",
        "on-primary-fixed-variant": "#004f58",
        "on-primary": "#00363d",
        "inverse-on-surface": "#2e3037",
        "on-surface": "#e1e2eb",
        "surface-tint": "#00daf3",
        "on-tertiary-container": "#775200",
        "on-primary-fixed": "#001f24",
        "primary": "#c3f5ff",
        "background": "#10131a",
        "on-secondary-fixed": "#2e004e",
        "on-background": "#e1e2eb",
        "surface-container-high": "#272a31",
        "tertiary-fixed-dim": "#ffba38",
        "surface-container": "#1d2026",
        "on-error-container": "#ffdad6",
        "primary-container": "#00e5ff",
        "on-tertiary-fixed": "#281900",
        "on-secondary-container": "#d7a4ff",
        "tertiary": "#ffe9cd",
        "surface-dim": "#10131a",
        "on-tertiary-fixed-variant": "#604100",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#00daf3",
        "tertiary-container": "#ffc769",
        "outline": "#849396",
        "tertiary-fixed": "#ffdeac",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-tertiary": "#432c00",
        "secondary-container": "#6d11ad",
        "surface-container-highest": "#32353c",
        "on-secondary-fixed-variant": "#6a0baa",
        "on-secondary": "#4c007d",
        "surface": "#10131a",
        "secondary-fixed-dim": "#e0b6ff",
        "surface-container-low": "#191c22",
        "on-surface-variant": "#bac9cc",
        "on-primary-container": "#00626e",
        "secondary-fixed": "#f2daff",
        "outline-variant": "#3b494c",
        "surface-variant": "#32353c",
        "inverse-surface": "#e1e2eb",
        "inverse-primary": "#006875"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ]
}
